apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - tempo-configmap.yaml
  - tempo-deployment.yaml
  - tempo-service.yaml
  - tempo-datasource.yaml
