apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268

    ingester:
      max_block_duration: 5m
      trace_idle_period: 10s
      complete_block_timeout: 30s
      lifecycler:
        ring:
          replication_factor: 1

    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 48h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        pool:
          max_workers: 20
          queue_depth: 1000

    metrics_generator:
      registry:
        collection_interval: 30s
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prom-stack-kube-prometheus-prometheus.observability.svc.cluster.local:9090/api/v1/write
            send_exemplars: true
            headers:
              "X-Scope-OrgID": "tempo"

    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics]
