apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: joke-app
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://grafana-agent.observability.svc.cluster.local:4318/v1/traces"
        - name: OTEL_SERVICE_NAME
          value: "joke-api"
