# Configuração adicional para o Traefik no K3s
# Este arquivo permite personalizar o Traefik Ingress Controller

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # Habilitar dashboard do Traefik (opcional)
    dashboard:
      enabled: true
      domain: traefik.labk3s.online

    # Configurações para melhorar desempenho e segurança
    additionalArguments:
      - --log.level=INFO
      - --api.insecure=false
      - --providers.kubernetesingress.ingressclass=traefik
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      
    # Configurações de recursos
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
        
    # Configurações do serviço
    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
        # Substitua pelo IP da sua VPS
        - YOUR_VPS_IP
      annotations:
        metallb.universe.tf/allow-shared-ip: traefik
