apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      automountServiceAccountToken: false  # Desabilitar montagem automática do token
      containers:
        - name: agent
          image: grafana/agent:v0.35.0
          args:
            - run
            - /etc/agent/agent.yaml
            - --server.http.listen-addr=0.0.0.0:12345
          ports:
            - containerPort: 12345
              name: http-metrics
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 14268
              name: jaeger-http
          volumeMounts:
            - name: config
              mountPath: /etc/agent
            - name: data
              mountPath: /tmp
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 500Mi
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 12345
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: grafana-agent-config
        - name: data
          emptyDir: {}
