apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: observability
  labels:
    app: grafana-agent
spec:
  selector:
    app: grafana-agent
  ports:
    - port: 12345
      targetPort: 12345
      name: http-metrics
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
    - port: 14268
      targetPort: 14268
      name: jaeger-http
