apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-otel-collector
  namespace: app
spec:
  selector:
    matchLabels:
      app: app-otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: app-otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:0.71.0
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 4317 # OTLP gRPC
          name: otlp-grpc
        - containerPort: 4318 # OTLP HTTP
          name: otlp-http
        - containerPort: 13133 # Health check
          name: health-check
        volumeMounts:
        - name: otel-config
          mountPath: /conf
        args:
        - --config=/conf/otel-collector-config
      volumes:
      - name: otel-config
        configMap:
          name: otel-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-otel-collector
  namespace: app
spec:
  selector:
    app: app-otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: health-check
    port: 13133
    targetPort: 13133
