apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: app
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      otlp:
        endpoint: otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 50
      memory_limiter:
        check_interval: 5s
        limit_mib: 100
    
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
