apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- frontend-nodeport.yaml
- api-route.yaml
- grafana-route.yaml

