apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: joke-app
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://grafana-agent.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "joke-backend"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "1.0"
