apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joke-app

resources:
  - ../../base

patches:
  - path: nginx-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
  - path: backend-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: backend
