apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Servidor do Let's Encrypt para produção
    server: https://acme-v02.api.letsencrypt.org/directory
    email: seu-email@exemplo.com  # Substitua pelo seu email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: traefik  # Usamos o Traefik como ingress controller
