name: Build and Deploy Joke App (All-in-one)

on:
  # Execução manual do workflow para build e deploy completo
  workflow_dispatch:

env:
  VERSION: ${{ github.sha }}

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    secrets: inherit

  build-backend:
    uses: ./.github/workflows/build-backend.yml
    secrets: inherit

  deploy:
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
